{% set name = "cx_Freeze" %}
{% set version = "8.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 491998d513f04841ec7967e2a3792db198597bde8a0c9333706b1f96060bdb35

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cxfreeze = cx_Freeze.cli:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - cx_logging >=3.1       # [win]
  run:
    - python
    - setuptools >=65.6.3
    - filelock >=3.12.3
    - packaging >=24.0
    - tomli >=2.0.1          # [py<311]
    - patchelf >=0.14,<0.18  # [linux]
    - dmgbuild >=1.6.1       # [osx]
    - cabarchive >=0.2.4     # [win]
    - cx_logging >=3.1       # [win]
    - py-lief >=0.15.1       # [win]
    - striprtf >=0.0.26      # [win]

test:
  imports:
    - cx_Freeze
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-timeout
    - pytest-xdist
  source_files:
    - pyproject.toml
    - samples
    - tests
  commands:
    - cxfreeze --version
    - pytest --dist=loadfile -nauto --no-cov -vv

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE.md
  summary: Create standalone executables from Python scripts, with the same performance and is cross-platform.

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
