{% set version = "6.7" %}

package:
  name: cx_freeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Freeze/cx_Freeze-{{ version }}.tar.gz
  sha256: 050f1dd133a04810bd7f38ac7ae3b290054acb2ff4f6e73f7a286266d153495d

build:
  skip: true  # [osx and py==39]
  number: 0
  script:
    # patch cx_Logging 3.0 - 3.1 will fix this
    - git clone https://github.com/anthony-tuininga/cx_Logging.git  # [win]
    - copy "cx_Logging\src\cx_Logging.h" "%PREFIX%\include\cx_Logging.h"  # [win]
    - set "PIP_NO_INDEX=False"  # [win]
    - {{ PYTHON }} -m pip install "cx_Logging>=3.0" --no-cache-dir  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cxfreeze = cx_Freeze.cli:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - {{ compiler('c') }}
    - pip
    - python
    - setuptools
  host:
    - pip
    - python
    - setuptools
    # ld: cannot find -lpython3.8
    - libpython-static  # [unix and py>=38]
  run:
    - python
    - setuptools
    - importlib-metadata >=3.1.1

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: README.md
  summary: create standalone executables from Python scripts

extra:
  recipe-maintainers:
    - jschueller
