{% set version = "6.8" %}

package:
  name: cx_freeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Freeze/cx_Freeze-{{ version }}.tar.gz
  sha256: 7eb48427ba125e320066e40d3ea3056200e023b2b984cc4b2085ad14f8bc94ed
  patches:
    - patch-1.diff  # [osx and py==39]

build:
  number: 0
  script:
    - set "PIP_NO_INDEX=False"  # [win]
    - {{ PYTHON }} -m pip install "cx_Logging>=3.0" --no-cache-dir  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cxfreeze = cx_Freeze.cli:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    # ld: cannot find -lpython3.8
    - libpython-static  # [unix and py>=38]
  run:
    - python
    - setuptools
    - importlib-metadata >=4.3.1

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: README.md
  summary: create standalone executables from Python scripts

extra:
  recipe-maintainers:
    - jschueller
