{% set version = "6.5.2" %}

package:
  name: cx_freeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Freeze/cx_Freeze-{{ version }}.tar.gz
  sha256: 869731afc624b511cdad0df2d3e8fb5433da488720838c02462a25dcdd37fcd4

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cxfreeze = cx_Freeze.main:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    # ld: cannot find -lpython3.8
    - libpython-static  # [unix and py>=38]
  run:
    - python
    - setuptools
    - importlib_metadata

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: README.md
  summary: create standalone executables from Python scripts

extra:
  recipe-maintainers:
    - jschueller
