{% set name = "cx_Freeze" %}
{% set version = "6.15.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04e63a345b6795be5a46999e190173a28d6d2cb51dcb4947fa13571a462ce336

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cxfreeze = cx_Freeze.cli:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=62.6
    - cx_logging >=3.1   # [win]
  run:
    - python
    - setuptools >=62.6
    - filelock >=3.11.0  # [linux]
    - patchelf >=0.14    # [linux]
    - cx_logging >=3.1   # [win]
    - py-lief >=0.12.0   # [win]

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: doc/src/license.rst
  summary: Create standalone executables from Python scripts, with the same performance and is cross-platform.

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
