{% set name = "cx_Freeze" %}
{% set version = "6.14.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9da31fa8e01d2dfdd603fa70e26390a65aea6dd62333c94d9f038b42aa055c8

build:
  number: 0
  script:
    - rm ${PREFIX}/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a  # [linux and py<=37]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cxfreeze = cx_Freeze.cli:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=61.2
    - cx_logging >=3.1  # [win]
  run:
    - python
    - setuptools >=61.2
    - patchelf >=0.14   # [linux]
    - cx_logging >=3.1  # [win]
    - py-lief >=0.12.0  # [win]

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: doc/src/license.rst
  summary: Create standalone executables from Python scripts, with the same performance and is cross-platform.

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
