{% set version = "6.9" %}

package:
  name: cx_freeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Freeze/cx_Freeze-{{ version }}.tar.gz
  sha256: 673aa3199af2ef87fc03a43a30e5d78b27ced2cedde925da89c55b5657da267b

build:
  number: 1
  script:
    - set "PIP_NO_INDEX=False"  # [win]
    - {{ PYTHON }} -m pip install "cx_Logging>=3.0" --no-cache-dir  # [win]
    - set "PIP_NO_INDEX=True"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cxfreeze = cx_Freeze.cli:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    # ld: cannot find -lpython3.8
    - libpython-static  # [unix and py>=38]
  run:
    - python
    - setuptools
    - importlib-metadata >=4.8.3
    - patchelf >=0.12   # [linux]
    - py-lief >=0.11.5  # [win]

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: README.md
  summary: create standalone executables from Python scripts

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
