{% set version = "6.5.3" %}

package:
  name: cx_freeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Freeze/cx_Freeze-{{ version }}.tar.gz
  sha256: e0d03cabcdf9b9c21354807ed9f06fa9481a8fd5a0838968a830f01a70820ff1
  patches:
    - nolto.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cxfreeze = cx_Freeze.main:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    # ld: cannot find -lpython3.8
    - libpython-static  # [linux and py>=38]
  run:
    - python
    - setuptools
    - importlib-metadata

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: README.md
  summary: create standalone executables from Python scripts

extra:
  recipe-maintainers:
    - jschueller
