{% set version = "6.3" %}

package:
  name: cx_freeze
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Freeze/cx_Freeze-{{ version }}.tar.gz
  sha256: 7702c0a87a3a14d4d0800867371385827564f074a3a78f3f97682ffc4d50384f

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cxfreeze = cx_Freeze.main:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: README.md
  summary: create standalone executables from Python scripts

extra:
  recipe-maintainers:
    - jschueller
