{% set name = "cx_Freeze" %}
{% set version = "6.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f3a30c9e3394f290655e346d3b460910656b30ac6347a87499bb5ad365c6e7c

build:
  number: 1
  script:
    - rm ${PREFIX}/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a  # [linux and py<=37]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cxfreeze = cx_Freeze.cli:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=59
    - importlib-metadata >=4.8.3
    - cx_logging >=3.0  # [win]
  run:
    - python
    - setuptools >=59
    - importlib-metadata >=4.8.3
    - packaging >=21.0
    - patchelf >=0.12   # [linux]
    - cx_logging >=3.0  # [win]
    - py-lief >=0.11.5  # [win]

test:
  imports:
    - cx_Freeze
  commands:
    - cxfreeze --version

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: doc/src/license.rst
  summary: Create standalone executables from Python scripts, with the same performance and is cross-platform.

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
