{% set name = "cx_Freeze" %}
{% set version = "7.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: c57f7101b4d35132464b1ec88cb8948c3b7c5b4ece4bb354c16091589cb33583

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cxfreeze = cx_Freeze.cli:main
    - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=65.6.3
    - typing_extensions >=4.10.0  # [py<310]
    - cx_logging >=3.1   # [win]
  run:
    - python
    - setuptools >=65.6.3
    - cabarchive >=0.2.4
    - filelock >=3.12.3
    - striprtf >=0.0.26
    - patchelf >=0.14    # [linux]
    - dmgbuild >=1.6.1   # [osx]
    - cx_logging >=3.1   # [win]
    - py-lief >=0.12.0   # [win]

test:
  imports:
    - cx_Freeze
  requires:
    - pytest
    - pytest-cov
    - pytest-datafiles
    - pytest-mock
    - pytest-timeout
    - pytest-xdist
  source_files:
    - pyproject.toml
    - cx_Freeze/icons
    - samples
    - tests
  commands:
    - cxfreeze --version
    - pytest -nauto --no-cov

about:
  home: https://marcelotduarte.github.io/cx_Freeze
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE.md
  summary: Create standalone executables from Python scripts, with the same performance and is cross-platform.

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
