schema_version: 1

context:
  name: cx_Freeze
  version: 8.5.0
  sha256: 4bdf7a4273e224fb98800785b72541f3c578107891529b5bd8068b5d0a19fd95

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cxfreeze = cx_Freeze.cli:main
      - cxfreeze-quickstart = cx_Freeze.setupwriter:main

requirements:
  host:
    - python
    - pip
    - setuptools >=78.1.1,<81
    - if: win
      then:
        - cx_logging >=3.1
  run:
    - python
    - freeze-core >=0.4.0
    - packaging >=24.0
    - setuptools >=78.1.1,<81
    - if: match(python, "<3.11")
      then:
        - tomli >=2.0.1
    - if: linux
      then:
        - filelock >=3.15.3
        - patchelf >=0.14,<0.18
    - if: osx
      then:
        - dmgbuild >=1.6.1
    - if: win
      then:
        - cx_logging >=3.1
        - py-lief >=0.15.1

tests:
  - python:
      imports:
        - cx_Freeze
      pip_check: false
  - files:
      source:
        - pyproject.toml
        - samples
        - tests
    requirements:
      run:
        - coverage >=7.10.3
        - pytest
        - pytest-mock
        - pytest-timeout
        - pytest-xdist
    script:
      - cxfreeze --version
      - if: not (osx and x86_64)
        then: coverage run || true

about:
  license: PSF-2.0
  license_file: LICENSE.md
  summary: Create standalone executables from Python scripts, with the same performance and is cross-platform.
  homepage: https://marcelotduarte.github.io/cx_Freeze

extra:
  recipe-maintainers:
    - marcelotduarte
    - jschueller
