travis:
  secure:
    BINSTAR_TOKEN: jUUUr5vi6feh1jVgQO/4Pd8sI3pAPWkihfMjSBBSGexmKoQeCk+wKZ/wnrOyiahrdLWgVZDZyEqIcwQDIPDjdaQxelQFeG4OEIoVqOy63b4oLZ8MBMKoz9ZzRP7eEc9vCm0I3kheawM9hX1GAUYXazYJciNbbM4p9m7v8lCaLYprKo5Ozi/6Qq9PskPU8AydHJdRyHPEJqIHwk+edMMX5TdGIZBt9yv1nuXqpSaQh6E1dNbFvpT7t1hKlzlDb3Pvx4us2t53NT3rV2TdESMMHnkxE18GaqO9FGhuG7wy4dXZuMWJ1KhJrBSsLCELaGsxUxaLdPy/7OQDZPZpQfDbiwp6l2Z0TsrU+mdubVDgk7tew9rmm/0cEGeG63w4FCEsDqbyRhCI2uKHiMRwohV5yomVnq8Zc9oFJ303O5I50yAEzcL8rx5C9/73kkCuTwF2lWw84/tvAM1BRHCUTLQgILTcByzKint6u9YXe1SdCtKbhSlCBrQ0+7jnlIIggwDGYUzpcH7H4lm3kQ1rsimVzpzgKZkAuCxv1jcTnL7JuTmRtdcrdbIzXnYdtB1/gbpjvnalNywYTTlvb2TsqVXm+eiaEVV9S7uR8kegRxItcanixfSEYxtmSZgtf5rk3LX2e03ak6vhses6Lvki1SJLOJh228Z1CgCK4G3EdVJe5r8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
